# Generated by Django 4.0.4 on 2023-06-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.PositiveIntegerField()),
                ('f_name', models.CharField(max_length=255, null=True)),
                ('f_size', models.CharField(max_length=50, null=True)),
                ('myfiles', models.FileField(upload_to='')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('db_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('is_build_succeeded', models.CharField(max_length=50, null=True)),
                ('dotnet_version', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Zipfile',
        ),
    ]
