# Generated by Django 4.0.4 on 2023-06-28 19:25

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zipfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNamesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Username must have at least 3 characters.')])),
                ('email', models.EmailField(max_length=254)),
                ('enable', models.BooleanField(default=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'UserNamesList',
            },
        ),
    ]
