# Generated by Django 4.0.4 on 2023-06-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfile',
            old_name='field_of_study',
            new_name='db_name',
        ),
        migrations.RenameField(
            model_name='zipfile',
            old_name='student_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='zipfile',
            old_name='first_name',
            new_name='is_build_succeeded',
        ),
        migrations.RenameField(
            model_name='zipfile',
            old_name='last_name',
            new_name='user_name',
        ),
    ]
