# Generated by Django 4.0.4 on 2023-07-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipfiles', '0002_usernameslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernameslist',
            old_name='username',
            new_name='user_name',
        ),
    ]
